ruby/config/routes.rb
Rails.application.routes.draw do

  resources :transactions, except: [:show]

  post :incoming, to: 'incoming#create'

  get 'transactions/dashboard'

  get 'transactions/cashflow'

  get 'welcome/about'

  root 'welcome#index'

end

ruby/app/models/cashflow_scope.rb
class CashflowScope
  attr_reader :date_to, :date_from

  def initialize(params)
    params ||= {}
    @date_from = parsed_date(params[:date_from], Date.today.beginning_of_year.to_s)
    @date_to = parsed_date(params[:date_to], Date.today.advance(:months => 1).to_s)
  end

  def scope
    Transaction.where('date BETWEEN ? AND ?', @date_from, @date_to )
  end

  private

  def parsed_date(date_string, default)
    Date.parse(date_string)
  rescue ArgumentError, TypeError
    default
  end
end

ruby/app/models/transaction.rb
class Transaction < ActiveRecord::Base
end

ruby/app/models/transaction_search.rb
class TransactionSearch
  attr_reader :date_from, :date_to

  def initialize(params)
    params ||= {}
    @date_from = parsed_date(params[:date_from], Date.today.at_beginning_of_month.to_s)
    @date_to = parsed_date(params[:date_to], Date.today.to_s)
  end

  def scope
    Transaction.where('date BETWEEN ? AND ?', @date_from, @date_to )
  end

  private

  def parsed_date(date_string, default)
    Date.parse(date_string)
  rescue ArgumentError, TypeError
    default
  end

end

ruby/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ruby/app/controllers/incoming_controller.rb
class IncomingController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create]

  def create
    date = Time.now
    amount = params["stripped-text"]
    type_of_transaction = params[:subject]
    category = params["stripped-signature"]
    category.gsub!("--", "")
    category.strip!

    transaction = Transaction.new(date: date, amount: amount, type_of_transaction: type_of_transaction, category: category)
    transaction.save!

    head 200
  end
end

ruby/app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  def index
    @search = TransactionSearch.new(params[:search])
    @transactions = @search.scope.order(date: :asc)
  end

  def new
    @transaction = Transaction.new
  end

  def create
    @transaction = Transaction.new(transaction_params)

    if @transaction.save
      flash[:notice] = "Transaction successfully created."
      redirect_to transactions_path
    else
      flash.now[:alert] = "Transaction could not be saved. Please try again."
      render :new
    end

  end

  def edit
    @transaction = Transaction.find(params[:id])
  end

  def update
    @transaction = Transaction.find(params[:id])
    @transaction.update_attributes(transaction_params)

    if @transaction.save
      flash[:notice] = "Transaction successfully updated."
      redirect_to transactions_path
    else
      flash.now[:alert] = "Transaction could not be saved. Please try again."
      render :edit
    end

  end

  def destroy
    @transaction = Transaction.find(params[:id])

    if @transaction.destroy
      flash[:notice] = "Your transaction was destroyed succesfully."
      redirect_to transactions_path
    else
      flash.now[:alert] = "Your transaction could not be destroyed. Please try again."
      redirect_to transactions_path
    end
  end

  def dashboard
    @search = TransactionSearch.new(params[:search])
    @transactions = @search.scope
    @cash = @transactions.where(category: "Cash", type_of_transaction: "Expense")
    @credit = @transactions.where(category: "Credit", type_of_transaction: "Expense")
    @total = @transactions.where(type_of_transaction: "Expense")
    @surplus = @transactions.where(category: "Balance")
  end

  def cashflow
    @search = CashflowScope.new(params[:search])
    @transactions = @search.scope
    @income = @transactions.where(type_of_transaction: "Income")
    @expenses = @transactions.where(category: "Cash")
  end

  private

  def transaction_params
    params.require(:transaction).permit(:date, :amount, :type_of_transaction, :cash_balance, :credit_balance, :category)
  end
end

ruby/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

ruby/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby/app/helpers/incoming_helper.rb
module IncomingHelper
end

ruby/app/helpers/transactions_helper.rb
module TransactionsHelper
end

ruby/app/helpers/welcome_helper.rb
module WelcomeHelper
end

ruby/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TrackIo</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Dashboard", transactions_dashboard_path %></li>
      <li><%= link_to "Transactions", transactions_path %></li>
      <li><%= link_to "Cashflow", transactions_cashflow_path %></li>
    </ul>
  </div>
  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

ruby/app/views/transactions/_form.html.erb
<%= form_for @transaction do |f| %>
  <%= f.label :date %>
  <%= f.date_field :date %>
  <%= f.label :amount %>
  <%= f.number_field :amount %>
  <%= f.label :type_of_transaction %>
  <%= f.select(:type_of_transaction, options_for_select([["Credit Due"], ["Credit Loan"], ["Expense"], ["Income"], ["Reimbursement"]])) %>
  <%= f.label :category %>
  <%= f.select(:category, options_for_select([["Balance"], ["Cash"], ["Credit"], ["Credit Due"], ["Condo Fee"], ["Electricity"], ["Gas"], ["Groceries"], ["Maid"], ["Loan Payment"], ["Other"], ["Reimbursement"], ["Salary"], ["Tv/Internet"]])) %>
  <%= f.submit "Save" %>
<% end %>

ruby/app/views/transactions/cashflow.html.erb
<div class="row">
  <h1>Cashflow</h1>
  <div class="pull-right range-query">
    <%= form_tag transactions_cashflow_path, method: :get do %>
      <%= text_field_tag 'search[date_from]', @search.date_from %>
      <%= text_field_tag 'search[date_to]', @search.date_to %>
      <%= submit_tag 'Search', class: 'btn search-button' %>
    <% end %>
  </div>
</div>
<div class="media">
  <div class="media-body">
    <table>
      <tbody>
        <tr>
          <td><h1>Cash</h1></td>
          <td><h3 class="amount"><%= number_to_currency(@income.sum(:amount), precision: 0) %></h3></td>
        </tr>
        <tr>
          <td><h1>Expenses</h1></td>
          <td><h3 class="amount"><%= number_to_currency(@expenses.sum(:amount), precision: 0) %></h3></td>
        </tr>
        <tr class="balance">
          <td><h3>Surplus/Deficit</h3></td>
          <td><h3 class="amount"><%= number_to_currency(@income.sum(:amount) - @expenses.sum(:amount), precision: 0) %></h3></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
<br>
<br>
<p><%= link_to 'New Transaction', new_transaction_path %></p>
<p><%= link_to 'Back', root_path %><p>

ruby/app/views/transactions/dashboard.html.erb
<div class="row">
  <h1>Dashboard</h1>
  <div class="pull-right range-query">
    <%= form_tag transactions_dashboard_path, method: :get do %>
      <%= text_field_tag 'search[date_from]', @search.date_from %>
      <%= text_field_tag 'search[date_to]', @search.date_to %>
      <%= submit_tag 'Search', class: 'btn search-button' %>
    <% end %>
  </div>
</div>
<div class="media">
  <div class="media-body">
    <table>
      <tbody>
        <tr>
          <td><h3>Cash Spent</h2></td>
          <td><h3 class="amount"><%= number_to_currency(@cash.sum(:amount), precision: 0) %></h3></td>
        </tr>
        <tr>
          <td><h3>Credit Spent</h2></td>
          <td><h3 class="amount"><%= number_to_currency(@credit.sum(:amount), precision: 0) %></h3></td>
        </tr>
        <tr>
          <td><h2>Total Spent</h2></td>
          <td><h3 class="amount"><%= number_to_currency(@total.sum(:amount), precision: 0)%></h2></td>
        </tr>
        <tr>
          <td><h1>Budget</h1></td>
          <td><h3 class="amount"><%= number_to_currency(10_000_000 - @total.sum(:amount), precision: 0) %></h3></td>
        </tr>
        <tr class="balance">
          <td><h3>Surplus/Deficit</h3></td>
          <td><h3 class="amount"><%= number_to_currency(@surplus.sum(:amount), precision: 0) %></h3></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
<br>
<br>
<p><%= link_to 'New Transaction', new_transaction_path %></p>
<p><%= link_to 'Back', root_path %><p>

ruby/app/views/transactions/edit.html.erb
<h1>Edit Transaction</h1>
<p><%= render partial: 'form', locals: {transaction: @transaction} %></p>

ruby/app/views/transactions/index.html.erb
<div class="row">
  <h1> All Transactions</h1>
  <p><%= link_to 'New Transaction', new_transaction_path %></p>
  <div class="pull-right range-query">
    <%= form_tag transactions_path, method: :get do %>
      <%= text_field_tag 'search[date_from]', @search.date_from %>
      <%= text_field_tag 'search[date_to]', @search.date_to %>
      <%= submit_tag 'Search', class: 'btn search-button' %>
    <% end %>
  </div>
</div>
<div class="media">
  <div class="media-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Type of Transaction</th>
          <th>Date</th>
          <th>Amount</th>
          <th>Category</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @transactions.each do |t| %>
            <tr>
              <td><%= t.type_of_transaction %></td>
              <td><%= t.date %></td>
              <td><%=number_to_currency(t.amount, precision: 0)%></td>
              <td><%= t.category %></td>
              <td><%= link_to 'Edit', edit_transaction_path(t), class: 'btn btn-default' %></td>
              <td><%= link_to 'Delete', t, method: :delete, class: 'btn btn-danger' %></td>
            </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<p><%= link_to 'Back', root_path %></p>

ruby/app/views/transactions/new.html.erb
<h1>New Transaction</h1>
<p><%= render partial: 'form', locals: {transaction: @transaction} %></p>

ruby/app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

ruby/app/views/welcome/index.html.erb
<h1>Welcome to track.io</h1>
<p>Track your networth and cashflow in real-time.</p>

<h2><%= link_to 'Transactions', transactions_path %></h2>

<h2><%= link_to 'Dashboard', transactions_dashboard_path %></h2>